export const Lookups_API={
  "matterCategory":{
    "get":"LawMtrCat/GetList",
    "create":"LawMtrCat/Create",
    "update":"LawMtrCat/Update"
  },
  "jurisdictions":{
    "get":"Law_Jurisdiction/GetList",
    "create":"Law_Jurisdiction/Create",
    "update":"Law_Jurisdiction/Update"
  },
  "judicature":{
    "get":"Law_Judicature/GetList",
    "create":"Law_Judicature/Create",
    "update":"Law_Judicature/Update"
  },
  "practiceArea":{
    "get":"Law_PractsArea/GetList",
    "create":"Law_PractsArea/Create",
    "update":"Law_PractsArea/Update",
    "delete":"Law_PractsArea/Delete"
  },
  "clientGroup":{
    "get":"ClientGroup/GetList",
    "create":"ClientGroup/Create",
    "update":"ClientGroup/Update"
  }
}
