export const Pre_Bill_Expenses_Columns_AR=[
    {
        field:'date',
        header:'Date',
        isSort:true
    },
    {
        field:'initial',
        header:'Initial',
        isSort:true
    },
    {
        field:'amount',
        header:'Amount',
        isSort:true
    },
    {
        field:'explanation',
        header:'Explanation',
    },
    {
        field:'hold',
        header:'Hold',
    },
]
export const Pre_Bill_Expenses_Columns_EN=[
    {
        field:'date',
        header:'Date',
        isSort:true
    },
    {
        field:'initial',
        header:'Initial',
        isSort:true
    },

    {
        field:'amount',
        header:'Amount',
        isSort:true
    },
    {
        field:'explanation',
        header:'Explanation',
    },
    {
        field:'hold',
        header:'Hold',
    },
]
export const Pre_Bill_Expenses_Columns_FR=[
    {
        field:'date',
        header:'Date',
        isSort:true
    },
    {
        field:'initial',
        header:'Initial',
        isSort:true
    },
    {
        field:'amount',
        header:'Amount',
        isSort:true
    },
    {
        field:'explanation',
        header:'Explanation',
    },
    {
        field:'hold',
        header:'Hold',
    },
]