export const Pre_Bill_Time_Fees_Columns_AR=[
    {
        field:'date',
        header:'Date',
        isSort:true
    },
    {
        field:'initial',
        header:'Initial',
        isSort:true
    },
    {
        field:'task',
        header:'Task',
        isSort:true
    },
    {
        field:'hours',
        header:'Hours',
        isSort:true
    },
    {
        field:'rate',
        header:'Rate',
        isSort:true
    },
    {
        field:'amount',
        header:'Amount',
        isSort:true
    },
    {
        field:'explanation',
        header:'Explanation',
    },
    {
        field:'hold',
        header:'Hold',
    },
]
export const Pre_Bill_Time_Fees_Columns_EN=[
    {
        field:'date',
        header:'Date',
        isSort:true
    },
    {
        field:'initial',
        header:'Initial',
        isSort:true
    },
    {
        field:'task',
        header:'Task',
        isSort:true
    },
    {
        field:'hours',
        header:'Hours',
        isSort:true
    },
    {
        field:'rate',
        header:'Rate',
        isSort:true
    },
    {
        field:'amount',
        header:'Amount',
        isSort:true
    },
    {
        field:'explanation',
        header:'Explanation',
    },
    {
        field:'hold',
        header:'Hold',
    },
]
export const Pre_Bill_Time_Fees_Columns_FR=[
    {
        field:'date',
        header:'Date',
        isSort:true
    },
    {
        field:'initial',
        header:'Initial',
        isSort:true
    },
    {
        field:'task',
        header:'Task',
        isSort:true
    },
    {
        field:'hours',
        header:'Hours',
        isSort:true
    },
    {
        field:'rate',
        header:'Rate',
        isSort:true
    },
    {
        field:'amount',
        header:'Amount',
        isSort:true
    },
    {
        field:'explanation',
        header:'Explanation',
    },
    {
        field:'hold',
        header:'Hold',
    },
]